# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5c97f91b28bf451d4493304480f9d5c7a6e3d287c1d84d6c52b9bdc4a5b45e9ea6966939703099d8c5621613c74e3ad11e226df6c6d568cd4440fa817609dcf

test:
  secret_key_base: 633bc90febd1e6db3e61324972c07af9e49c96ad9b315ae8d1edf02ffd34be58d10ced0c6d8e4139fcc8a02c9f676512a62aedb3d4319f2bf8f1673b6076efe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
